import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@park-ui/tailwind-plugin/preset.css'
import { cn } from "~/shared/lib/cn";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={cn(inter.className, 'bg-black-06')}>
				{children}
			</body>
		</html>
	);
}
