import type { Metadata } from "next";
import "./globals.css";
import '@park-ui/tailwind-plugin/preset.css'
import { cn } from "~/shared/lib/cn";

import { fontInter } from "~/shared/assets/fonts/inter";
import { fontManrope } from "~/shared/assets/fonts/manrope";

const fontVariables = [fontInter.variable, fontManrope.variable];

export const metadata: Metadata = {
	title: "Sella.me",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={cn(...fontVariables, 'bg-black-06 text-white font-inter')}>
				{children}
			</body>
		</html>
	);
}
